name: Tests

on:
  pull_request:
    types: [opened, edited]

jobs:
  test:
    name: run tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out REPO
        uses: actions/checkout@v2
      - name: Setup NODE
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - name: Have fun
        run: yarn test
